create table Inventory.Stocks (
        Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
       Version INTEGER not null,
       ClientPrimaryKey INTEGER UNSIGNED,
       Timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
       Status INTEGER default 0  not null,
       WaybillLineId INTEGER UNSIGNED,
       AddressId INTEGER UNSIGNED,
       CreatedByUserId INTEGER UNSIGNED,
       ProductId INTEGER UNSIGNED,
       CatalogId INTEGER UNSIGNED,
       Product VARCHAR(255),
       ProducerId INTEGER UNSIGNED,
       Producer VARCHAR(255),
       CountryCode VARCHAR(255),
       Country VARCHAR(255),
       Period VARCHAR(255),
       Exp DATETIME,
       SerialNumber VARCHAR(255),
       Certificates VARCHAR(255),
       Unit VARCHAR(255),
       ExciseTax DECIMAL(19,5),
       BillOfEntryNumber VARCHAR(255),
       VitallyImportant TINYINT(1),
       ProducerCost DECIMAL(19,5),
       RegistryCost DECIMAL(19,5),
       SupplierPriceMarkup DECIMAL(19,5),
       SupplierCostWithoutNds DECIMAL(19,5),
       SupplierCost DECIMAL(19,5),
       Nds INTEGER,
       NdsAmount DECIMAL(19,5),
       Barcode VARCHAR(255),
       Quantity DECIMAL(19,5) default 0  not null,
       SupplyQuantity DECIMAL(19,5) default 0  not null,
       RetailCost DECIMAL(19,5),
       RetailMarkup DECIMAL(19,5),
       primary key (Id)
    );
alter table Inventory.Stocks add index (AddressId), add constraint FK_Inventory_Stocks_AddressId foreign key (AddressId) references Customers.Addresses (Id);
alter table Inventory.Stocks add index (CreatedByUserId), add constraint FK_Inventory_Stocks_CreatedByUserId foreign key (CreatedByUserId) references Customers.Users (Id);
