	use Inventory;
    create table Inventory.DisplacementDocs (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
		UserId int unsigned,
       Timestamp DATETIME default '0001-01-01'  not null,
       Date DATETIME default '0001-01-01'  not null,
       CloseDate DATETIME,
       Status INTEGER default 0  not null,
       AddressId INTEGER UNSIGNED,
       DstAddressId INTEGER UNSIGNED,
       SupplierSum DECIMAL(19,5) default 0  not null,
       PosCount INTEGER default 0  not null,
       Comment VARCHAR(255),
       Error VARCHAR(255),
       primary key (Id)
    );

    create table Inventory.UnpackingDocs (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
		UserId int unsigned,
       Timestamp DATETIME default '0001-01-01'  not null,
       Date DATETIME default '0001-01-01'  not null,
       AddressId INTEGER UNSIGNED,
       Status INTEGER default 0  not null,
       CloseDate DATETIME,
       SrcRetailSum DECIMAL(19,5),
       RetailSum DECIMAL(19,5),
       Comment VARCHAR(255),
       LinesCount INTEGER default 0  not null,
       primary key (Id)
    );

    create table Inventory.ReturnDocs (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
		UserId int unsigned,
       Timestamp DATETIME default '0001-01-01'  not null,
       Date DATETIME default '0001-01-01'  not null,
       CloseDate DATETIME,
       Status INTEGER default 0  not null,
       AddressId INTEGER UNSIGNED,
       SupplierId INTEGER UNSIGNED,
       RetailSum DECIMAL(19,5) default 0  not null,
       SupplierSumWithoutNds DECIMAL(19,5) default 0  not null,
       SupplierSum DECIMAL(19,5) default 0  not null,
       PosCount INTEGER default 0  not null,
       Comment VARCHAR(255),
       Error VARCHAR(255),
       primary key (Id)
    );
    create table Inventory.InventoryDocs (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
		UserId int unsigned,
       Timestamp DATETIME default '0001-01-01'  not null,
       Date DATETIME default '0001-01-01'  not null,
       AddressId INTEGER UNSIGNED,
       Status INTEGER default 0  not null,
       CloseDate DATETIME,
       SupplySumWithoutNds DECIMAL(19,5),
       SupplySum DECIMAL(19,5),
       RetailSum DECIMAL(19,5),
       LinesCount DECIMAL(19,5) default 0  not null,
       Comment VARCHAR(255),
       primary key (Id)
    );

    create table ReassessmentDocs (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
		UserId int unsigned,
       Timestamp DATETIME default '0001-01-01'  not null,
       Date DATETIME default '0001-01-01'  not null,
       AddressId INTEGER UNSIGNED,
       Status INTEGER default 0  not null,
       CloseDate DATETIME,
       SrcRetailSum DECIMAL(19,5),
       SupplySumWithoutNds DECIMAL(19,5),
       SupplySum DECIMAL(19,5),
       RetailSum DECIMAL(19,5),
       LinesCount INTEGER default 0  not null,
       Comment VARCHAR(255),
       Error VARCHAR(255),
       primary key (Id)
    );

    create table WriteoffDocs (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
		UserId int unsigned,
       Timestamp DATETIME default '0001-01-01'  not null,
       Date DATETIME default '0001-01-01'  not null,
       AddressId INTEGER UNSIGNED,
       ReasonId INTEGER UNSIGNED,
       Status INTEGER default 0  not null,
       CloseDate DATETIME,
       SupplySumWithoutNds DECIMAL(19,5),
       SupplySum DECIMAL(19,5),
       RetailSum DECIMAL(19,5),
       LinesCount DECIMAL(19,5) default 0  not null,
       Comment VARCHAR(255),
       Error VARCHAR(255),
       primary key (Id)
    );

   create table UnpackingLines (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
       Quantity DECIMAL(19,5) default 0  not null,
       RetailCost DECIMAL(19,5),
       SrcQuantity DECIMAL(19,5) default 0  not null,
       SrcRetailCost DECIMAL(19,5),
       SrcStockId INTEGER UNSIGNED,
       DstStockId INTEGER UNSIGNED,
       Barcode VARCHAR(255),
       Product VARCHAR(255),
       ProductId INTEGER UNSIGNED,
       CatalogId INTEGER UNSIGNED,
       Producer VARCHAR(255),
       ProducerId INTEGER UNSIGNED,
       SerialNumber VARCHAR(255),
       Certificates VARCHAR(255),
       ProducerCost DECIMAL(19,5),
       RegistryCost DECIMAL(19,5),
       RetailMarkup DECIMAL(19,5),
       SupplierCost DECIMAL(19,5),
       SupplierCostWithoutNds DECIMAL(19,5),
       SupplierPriceMarkup DECIMAL(19,5),
       ExciseTax DECIMAL(19,5),
       BillOfEntryNumber VARCHAR(255),
       VitallyImportant TINYINT(1),
       SupplyQuantity DECIMAL(19,5) default 0  not null,
       UnpackingDocId INTEGER UNSIGNED,
       primary key (Id)
    );

    create table WriteoffLines (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
       WaybillLineId INTEGER UNSIGNED,
       Exp DATETIME,
       Period VARCHAR(255),
       Quantity DECIMAL(19,5) default 0  not null,
       StockId INTEGER UNSIGNED,
       Barcode VARCHAR(255),
       Product VARCHAR(255),
       ProductId INTEGER UNSIGNED,
       CatalogId INTEGER UNSIGNED,
       Producer VARCHAR(255),
       ProducerId INTEGER UNSIGNED,
       SerialNumber VARCHAR(255),
       Certificates VARCHAR(255),
       ProducerCost DECIMAL(19,5),
       RegistryCost DECIMAL(19,5),
       RetailCost DECIMAL(19,5),
       RetailMarkup DECIMAL(19,5),
       SupplierCost DECIMAL(19,5),
       SupplierCostWithoutNds DECIMAL(19,5),
       SupplierPriceMarkup DECIMAL(19,5),
       ExciseTax DECIMAL(19,5),
       BillOfEntryNumber VARCHAR(255),
       VitallyImportant TINYINT(1),
       SupplyQuantity DECIMAL(19,5) default 0  not null,
       WriteoffDocId INTEGER UNSIGNED,
       primary key (Id)
    );

  create table DisplacementLines (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
       WaybillLineId INTEGER UNSIGNED,
       Quantity DECIMAL(19,5) default 0  not null,
       Period VARCHAR(255),
       SrcStockId INTEGER UNSIGNED,
       DstStockId INTEGER UNSIGNED,
       Barcode VARCHAR(255),
       Product VARCHAR(255),
       ProductId INTEGER UNSIGNED,
       CatalogId INTEGER UNSIGNED,
       Producer VARCHAR(255),
       ProducerId INTEGER UNSIGNED,
       SerialNumber VARCHAR(255),
       Certificates VARCHAR(255),
       ProducerCost DECIMAL(19,5),
       RegistryCost DECIMAL(19,5),
       RetailCost DECIMAL(19,5),
       RetailMarkup DECIMAL(19,5),
       SupplierCost DECIMAL(19,5),
       SupplierCostWithoutNds DECIMAL(19,5),
       SupplierPriceMarkup DECIMAL(19,5),
       ExciseTax DECIMAL(19,5),
       BillOfEntryNumber VARCHAR(255),
       VitallyImportant TINYINT(1),
       SupplyQuantity DECIMAL(19,5) default 0  not null,
       DisplacementDocId INTEGER UNSIGNED,
       primary key (Id)
    );

    create table ReturnLines (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
       WaybillLineId INTEGER UNSIGNED,
       Quantity DECIMAL(19,5) default 0  not null,
       StockId INTEGER UNSIGNED,
       Barcode VARCHAR(255),
       Product VARCHAR(255),
       ProductId INTEGER UNSIGNED,
       CatalogId INTEGER UNSIGNED,
       Producer VARCHAR(255),
       ProducerId INTEGER UNSIGNED,
       SerialNumber VARCHAR(255),
       Certificates VARCHAR(255),
       ProducerCost DECIMAL(19,5),
       RegistryCost DECIMAL(19,5),
       RetailCost DECIMAL(19,5),
       RetailMarkup DECIMAL(19,5),
       SupplierCost DECIMAL(19,5),
       SupplierCostWithoutNds DECIMAL(19,5),
       SupplierPriceMarkup DECIMAL(19,5),
       ExciseTax DECIMAL(19,5),
       BillOfEntryNumber VARCHAR(255),
       VitallyImportant TINYINT(1),
       SupplyQuantity DECIMAL(19,5) default 0  not null,
       ReturnDocId INTEGER UNSIGNED,
       primary key (Id)
    );
    create table InventoryLines (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
       Quantity DECIMAL(19,5) default 0  not null,
       Period VARCHAR(255),
       StockId INTEGER UNSIGNED,
       Barcode VARCHAR(255),
       Product VARCHAR(255),
       ProductId INTEGER UNSIGNED,
       CatalogId INTEGER UNSIGNED,
       Producer VARCHAR(255),
       ProducerId INTEGER UNSIGNED,
       SerialNumber VARCHAR(255),
       Certificates VARCHAR(255),
       ProducerCost DECIMAL(19,5),
       RegistryCost DECIMAL(19,5),
       RetailCost DECIMAL(19,5),
       RetailMarkup DECIMAL(19,5),
       SupplierCost DECIMAL(19,5),
       SupplierCostWithoutNds DECIMAL(19,5),
       SupplierPriceMarkup DECIMAL(19,5),
       ExciseTax DECIMAL(19,5),
       BillOfEntryNumber VARCHAR(255),
       VitallyImportant TINYINT(1),
       SupplyQuantity DECIMAL(19,5) default 0  not null,
       InventoryDocId INTEGER UNSIGNED,
       primary key (Id)
    );

    create table ReassessmentLines (
        Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
		ClientPrimaryKey int unsigned,
       Exp DATETIME,
       Period VARCHAR(255),
       RetailCost DECIMAL(19,5),
       RetailMarkup DECIMAL(19,5),
       SrcRetailMarkup DECIMAL(19,5),
       SrcRetailCost DECIMAL(19,5),
       Quantity DECIMAL(19,5) default 0  not null,
       SrcStockId INTEGER UNSIGNED,
       DstStockId INTEGER UNSIGNED,
       Barcode VARCHAR(255),
       Product VARCHAR(255),
       ProductId INTEGER UNSIGNED,
       CatalogId INTEGER UNSIGNED,
       Producer VARCHAR(255),
       ProducerId INTEGER UNSIGNED,
       SerialNumber VARCHAR(255),
       Certificates VARCHAR(255),
       ProducerCost DECIMAL(19,5),
       RegistryCost DECIMAL(19,5),
       SupplierCost DECIMAL(19,5),
       SupplierCostWithoutNds DECIMAL(19,5),
       SupplierPriceMarkup DECIMAL(19,5),
       ExciseTax DECIMAL(19,5),
       BillOfEntryNumber VARCHAR(255),
       VitallyImportant TINYINT(1),
       SupplyQuantity DECIMAL(19,5) default 0  not null,
       ReassessmentDocId INTEGER UNSIGNED,
       primary key (Id)
    );
