use Inventory;
CREATE TABLE `stockactions` (
	`Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`UserId` INT(10) UNSIGNED NULL DEFAULT '0',
	`DisplayDoc` VARCHAR(255) NULL DEFAULT NULL,
	`NumberDoc` VARCHAR(255) NULL DEFAULT NULL,
	`FromIn` VARCHAR(255) NULL DEFAULT NULL,
	`OutTo` VARCHAR(255) NULL DEFAULT NULL,
	`ActionType` INT(11) NOT NULL DEFAULT '0',
	`TypeChange` INT(11) NOT NULL DEFAULT '0',
	`ClientStockId` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`SourceStockId` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	`SourceStockVersion` INT(11) NULL DEFAULT NULL,
	`Quantity` DECIMAL(19,5) NOT NULL DEFAULT '0.00000',
	`RetailCost` DECIMAL(19,5) NULL DEFAULT NULL,
	`RetailMarkup` DECIMAL(19,5) NULL DEFAULT NULL,
	`DiscountSum` DECIMAL(19,5) NULL DEFAULT NULL,
	`Version` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
);

CREATE TABLE `serverversion` (
	`Id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`UserId` INT(10) UNSIGNED NULL DEFAULT '0',
	PRIMARY KEY (`Id`)
);

CREATE TABLE `clientversion` (
	`Id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Version` BIGINT(20) UNSIGNED NULL DEFAULT '0',
	`UserId` INT(10) UNSIGNED NULL DEFAULT '0',
	PRIMARY KEY (`Id`)
);